### ISSUE TITLE
Server Error 500 after deleting a concept definition

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#409] opened 2017-03-27 17:15 UTC
The following URL gives a Server Error 500:

https://www.courselets.org/ct/teach/courses/25/units/123/concepts/

I encountered this error after deleting a lesson that defined a concept "Most recent common ancestor"

**Comment by maxsocl** [comment] 2017-03-28 11:11
@cjlee112 Fixed in DB.

Reason for issue to be fixed in prod DB - I cant reproduce it locally and on staging.
So if it is a bug - we need steps to reproduce.
Currently I can see couple of ConceptLink objects linked to <Concept: Most recent common ancestor> and to <Lesson: Ancestors of Human and Chimp?> (several ConceptLinks) but these lessons have no UnitLesson objects. Somehow `UnitLesson` objects were deleted. And I cant reproduce this flow using standard UI.

**Closed** 2018-10-16 19:32 UTC
Labels: Bug, Question
