### ISSUE TITLE
[Bug] It is possible to save Concept without Title nad Description

### ISSUE THREAD

**Issue by artbybluk** [cjlee112/socraticqs2#148] opened 2016-03-02 15:39 UTC
**Steps:**
Go to https://staging.courselets.org/ct/ ( admin / testonly )
Go to any Course
Go to any Concept
Go to "Edit" imput
Delete all info in "Title" and "Text" fields, and replace it with some gaps by typing Spacebar
Click "Update" button
**Actual result:** Course without Title and Text was created http://prntscr.com/aa6lbl
**Expected result:** Message "This field are required" should appear

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367179559267)

**Comment by maxsocl** [comment] 2016-05-18 15:41
@artbybluk I can't reproduce this issue.

<img width="1144" alt="screen shot 2016-05-18 at 6 40 04 pm" src="https://cloud.githubusercontent.com/assets/877401/15365221/1f84546c-1d28-11e6-83bb-74807cb2d6e3.png">

**Comment by maxsocl** [comment] 2016-05-19 11:39
@artbybluk Fixed

**Comment by cmltaWt0** [comment] 2018-10-16 16:51
1b1d0a8ec93141f048c54ec42864a1576cbcac7b

**Comment by redilonka** [comment] 2019-03-04 14:38
@cmltaWt0 please merge your fix to development

**Comment by redilonka** [comment] 2019-11-28 14:11
fixed in Tagged release v1.7.0

**Closed by redilonka** 2019-11-28 14:11 UTC
Labels: Bug, Need to test, Question
