### ISSUE TITLE
prevent multiple enrollments in the same class

### ISSUE THREAD

**Issue by cjlee112** [cjlee112/socraticqs2#93] opened 2015-09-29 18:13 UTC
One minor issue that caused a bit of confusion the first day of C260A was that some students unwittingly enrolled twice in the course: once via the LTI mechanism (which is how I told them to access Courselets; this gives them the status "enrolled student"); and a second time as "self-study" presumably by clicking the title of the course on the "Public Courses" page (/ct/courses/).  Being enrolled in the same course in two different ways causes various kinds of confusion; for example when students view the "Your Courses" page (/ct/) they are shown *two* separate buttons for joining my Live Session.

If a student is already enrolled in a course, we should definitely not create any additional enrollment for them in that course, and we should also consider hiding that course from the Public Courses list that invites them to enroll in more courses...

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/138308180149321/138367480187518)

**Comment by cjlee112** [comment] 2015-09-29 18:32
NB: workaround for this situation is that I think the student can just click the first of the two "Join Live Session" buttons, and everything should work fine (it probably doesn't matter which of the two buttons they click...)

**Comment by cjlee112** [comment] 2015-10-01 20:55
I see that the `courses_subscribe()` view is enrolling students without checking whether they are already enrolled with some other role.  Note also that the Django docs explicitly say not to use `get_or_create()` in a GET request, as this view is doing.  I think enrolment in a course should be a POST event.  This code needs to be reviewed and improved.

**Comment by cjlee112** [comment] 2015-10-01 21:01
Actually, I don't understand why the `courses_subscribe()` view even exists -- it is not a view!  This code should just be the POST request handler for the `courses()` view.

**Comment by cjlee112** [comment] 2015-10-01 21:18
This GET vs. POST distinction is a big reason why students are accidentally enrolling twice in the course: they (sensibly) don't expect just clicking a link to create a course enrolment (GET is not supposed to change database state). They expect such a big event to be signalled by a POST style submission mechanism.

**Comment by maxsocl** [comment] 2015-10-08 13:38
> Actually, I don't understand why the courses_subscribe() view even exists -- it is not a view! This code should just be the POST request handler for the courses() view.

@cjlee112 This view was intended to handle subscribe actions (finally it should be a POST action of course).
But this view was created for future project design and now we have  started discussion about more obvious way for users to Enroll(Subscribe) into Courses.
Such actions should be implemented via Ajax requests and obviously we need an Ajax request handler. I supposed to use `courses_subscribe` view for this goal.

**Comment by maxsocl** [comment] 2017-01-21 13:49
@cjlee112 do we still need this?

**Comment by cmltaWt0** [comment] 2018-10-16 13:05
Fixed in https://github.com/cjlee112/socraticqs2/commit/1d1a8ac94d148590e62fecc2614b8d826fb29f17 and didn't an issue in the current UI.

**Closed** 2018-10-16 13:04 UTC
Labels: Bug
